CREATE TABLE IF NOT EXISTS translation(
`en` varchar(40),
`ach` varchar(40),
`af` varchar(40),
`ak` varchar(40),
`am` varchar(40),
`an` varchar(40),
`ar` varchar(40),
`as` varchar(40),
`az` varchar(40),
`bg` varchar(40),
`bm` varchar(40),
`bn` varchar(40),
`br` varchar(40),
`bs` varchar(40),
`ca` varchar(40),
`cy` varchar(40),
`da` varchar(40),
`de` varchar(40),
`dsb` varchar(40),
`es` varchar(40),
`eu` varchar(40),
`fa` varchar(40),
`ff` varchar(40),
`fj` varchar(40),
`fo` varchar(40),
`fr` varchar(40),
`ga` varchar(40),
`gl` varchar(40),
`gnBO` varchar(40),
`gnPY` varchar(40),
`gu` varchar(40),
`ha` varchar(40),
`haw` varchar(40),
`he` varchar(40),
`hi` varchar(40),
`hr` varchar(40),
`hsb` varchar(40),
`ht` varchar(40),
`hu` varchar(40),
`hy` varchar(40),
`id` varchar(40),
`is` varchar(40),
`it` varchar(40),
`kk` varchar(40),
`km` varchar(40),
`kn` varchar(40),
`ko` varchar(40),
`ks` varchar(40),
`ku` varchar(40),
`lg` varchar(40),
`ln` varchar(40),
`lt` varchar(40),
`lv` varchar(40),
`mg` varchar(40),
`mk` varchar(40),
`ml` varchar(40),
`mr` varchar(40),
`ms` varchar(40),
`my` varchar(40),
`nb` varchar(40),
`nd` varchar(40),
`np` varchar(40),
`nl` varchar(40),
`ny` varchar(40),
`or` varchar(40),
`pa` varchar(40),
`pl` varchar(40),
`ps` varchar(40),
`pt` varchar(40),
`rn` varchar(40),
`ro` varchar(40),
`rw` varchar(40),
`sd` varchar(40),
`si` varchar(40),
`sk` varchar(40),
`sl` varchar(40),
`sm` varchar(40),
`sq` varchar(40),
`sr` varchar(40),
`ss` varchar(40),
`su` varchar(40),
`sv` varchar(40),
`sw` varchar(40),
`ta` varchar(40),
`te` varchar(40),
`tk` varchar(40),
`tl` varchar(40),
`tn` varchar(40),
`tr` varchar(40),
`ts` varchar(40),
`tt` varchar(40),
`ug` varchar(40),
`uk` varchar(40),
`ur` varchar(40),
`uz` varchar(40),
`vec` varchar(40),
`vi` varchar(40),
`wa` varchar(40),
`wo` varchar(40),
`xh` varchar(40),
`yo` varchar(40),
`zu` varchar(40)
 )ENGINE=InnoDB DEFAULT CHARSET=utf8;

 CREATE TABLE IF NOT EXISTS users(
  `user_key` varchar(40) NOT NULL ,
  `username` varchar(40) NOT NULL ,
  `pwd` varchar(255) NOT NULL,
  `fullname` varchar(40) NOT NULL,
  `birthday` date NOT NULL,
  `email` varchar(40) NOT NULL,
  `language` varchar(40) NOT NULL,
  PRIMARY KEY (`user_key`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE translation ADD approved INT NOT NULL DEFAULT 1;

  CREATE TABLE IF NOT EXISTS sessions(
   `sid` varchar(40) NOT NULL ,
   `expiry` int(10) unsigned NOT NULL,
   `data` text NOT NULL,
   PRIMARY KEY (`sid`)
   )ENGINE=InnoDB DEFAULT CHARSET=latin1;

   CREATE TABLE IF NOT EXISTS admin(
    `id` INT NOT NULL AUTO_INCREMENT,
    `username` varchar(40) NOT NULL ,
    `pwd` varchar(255) NOT NULL,
    PRIMARY KEY (`id`)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

  load data infile 'translations.txt' into table translation
  fields terminated by ';';
